### ISSUE TITLE
Docker中搭建本地的ELK

### ISSUE THREAD

**Issue by zuhd** [zuhd/blog#22]
sudo docker run -d --name elasticsearch --net elastic -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.13.3

sudo docker run -d --name logstash --net elastic -p 127.0.0.1:5044:5044 -v /home/hefehoo/elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf logstash:7.13.3

sudo docker run -d --name kibana --net elastic -p 127.0.0.1:5601:5601 -v /home/hefehoo/elk/kibana.yml:/usr/share/kibana/config/kibana.yml kibana:7.13.3

//sudo docker run -d --name filebeat --net elastic -v /home/hefehoo/elk/filebeat.yml:/usr/share/filebeat/filebeat.yml docker.elastic.co/beats/filebeat:7.13.3

echo '{"message": "hello world"}' | nc localhost 5044

也可以用docker compose，更方便

docker-compose.yml 

```yaml
version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.0
    container_name: logstash
    volumes:
      - ./logstash-config/:/usr/share/logstash/pipeline/
    ports:
      - "5000:5000"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana
    ports:
      - "5601:5601"
```

logstash-config/logstash.conf

```conf
input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "logs"
  }
}
```

docker-compose up -d
